version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql-bad
    ports:
      - "29454:3000"
    depends_on:
      - mongodb
